### ISSUE TITLE
Recorded mp4 replay error on iOS

### ISSUE THREAD

**Issue by Honghe** [foss-project/green-recorder#100]
# Environment
- GreenRecorder 3.1
- Ubuntu 16.04
- Wechat 6.7 on iOS 11.4
- Safari on iOS 11.4

# Phonomenon
- Wechat, The file seems like broken, although can replay.
![image](https://user-images.githubusercontent.com/1092722/42683616-6a470414-86c0-11e8-8319-c2b6978dc66a.png)
- Safari, can not open and play

# Recorded mp4 file

[2018-07-13 17:06:29.303573.mp4.tar.gz](https://github.com/foss-project/green-recorder/files/2192056/2018-07-13.17.06.29.303573.mp4.tar.gz)

# Another mp4 file play OK on iOS
This file not generated from GreenRecorder.

[demo_rain_animation.mp4.tar.gz](https://github.com/foss-project/green-recorder/files/2192072/demo_rain_animation.mp4.tar.gz)

**Comment by mhsabbagh** [comment]
Please provide more description. I have no idea what you mean by "iOS 11.4".
