### ISSUE TITLE
resolution selection?

### ISSUE THREAD

**Issue by hetzbh** [foss-project/green-recorder#102]
Hi,
I just found out green recorder and it's great.
One thing that is missing, IMHO, is selecting a resolution window, so I can select a resolution and resize the apps to this window and then record the video. This helps a lot when recording for Youtube.

**Comment by mhsabbagh** [comment]
Hi.

Can you please explain more? Green Recorder allows you to capture a specific area, so for example if you want to capture a 600x600 area on your screen and drag windows to it and then move them out for a screencast, you can do that.
