### ISSUE TITLE
Python Error On Manjaro

### ISSUE THREAD

**Issue by Noah11012** [foss-project/green-recorder#105]
I am running Manjaro and installed Green Recorder through the AUR green-recorder-git package.

This is the error I get:

```
You are recording on: x11
Traceback (most recent call last):
  File "/usr/bin/green-recorder", line 352, in <module>
    delayadjustment.set_value(int(config.get('Options', 'delay')))
  File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'Options'
```

**Comment by mhsabbagh** [comment]
What are the contents of /home/<youruser>/.config/green-recorder/config.ini?

**Comment by Noah11012** [comment]
Nothing:

```
➜  ~  cat /home/noah/.config/green-recorder/config.ini
➜  ~  
```

**Comment by mhsabbagh** [comment]
For some reason the configurations are not in your supposed config file, here's for example my file:

`[Options]
frames = 30
delay = 0
folder = file:///home/mhsabbagh/Videos
command = 
filename = 
videoswitch = True
audioswitch = True
mouseswitch = True
followmouseswitch = False
`

Try placing it there (with changing the "folder" in your videos folder path) and see.

**Comment by Noah11012** [comment]
Thanks for your help.

This is the output I now get:

```
You are recording on: x11
Traceback (most recent call last):
  File "/usr/bin/green-recorder", line 361, in <module>
    videoswitch.set_state(checkbool(config.get('Options', 'videocheck')))
  File "/usr/lib/python2.7/ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
ConfigParser.NoOptionError: No option 'videocheck' in section: 'Options'
```

**Comment by mhsabbagh** [comment]
Turns out the name of the default configuration options was different than the program expects. I fixed it now but you can replace the contents with this:

```
[Options]
frames = 30
delay = 0
folder = file:///home/mhsabbagh/Videos
command = 
filename = 
videocheck = True
audiocheck = True
mousecheck = True
followmousecheck = False
```

Thank you for your report!

**Comment by levimake** [comment]
> For some reason the configurations are not in your supposed config file, here's for example my file:
> 
> ```
> [Options]
> frames = 30
> delay = 0
> folder = file:///home/mhsabbagh/Videos
> command = 
> filename = 
> videoswitch = True
> audioswitch = True
> mouseswitch = True
> followmouseswitch = False
> ```
> 
> Try placing it there (with changing the "folder" in your videos folder path) and see.

In the config from the latest build, there is a small error in the config file. My config file looked like this :

> [Options]
> frames = 30
> delay = 0
> folder = file:///home/levis
> command = 
> filename = 
> videocheck = True
> audiocheck = True
> mousecheck = True
> followmousecheck = False

I got the same error as this issue and I changed all those last four lines (replaced check to switch like you've given). 

I replaced it to this : 

> [Options]
> frames = 30
> delay = 0
> folder = file:///home/levis
> command =
> filename =
> videoswitch = True
> audioswitch = True
> mouseswitch = True
> followmouseswitch = False

Voila ! Everything worked :) 
Thanks for this great project as I couldn't get any other screen recorder for my SWAY wm.
