### ISSUE TITLE
add option to show all keypresses visually

### ISSUE THREAD

**Issue by jpritikin** [foss-project/green-recorder#109]
For making tutorials, it is often helpful to show exactly which key was pressed visually. It can also be helpful to show which mouse button is pressed.

**Comment by mhsabbagh** [comment]
Thank you for your suggestion.

I have no intention to include that right now in the program. But for your usage, you can simply launch key-mon before running the recorder and then start recording: https://github.com/scottkirkwood/key-mon

**Comment by jpritikin** [comment]
Ah perfect.
