### ISSUE TITLE
No option 'videoswitch' in section: 'Options'

### ISSUE THREAD

**Issue by neerajrajpoot** [foss-project/green-recorder#110]
I am trying to run green-recorder on debian 9.2. While trying to run with the luncher it's getting crashed without any error and when i am trying to run the same through the command line getting the error mentioned below please note that same logs are sent in syslog as well : 

You are recording on: xorg
Traceback (most recent call last):
  File "/usr/local/bin/green-recorder", line 339, in <module>
    videoswitch.set_active(checkbool(config.get('Options', 'videoswitch')))
  File "/usr/lib/python2.7/ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
ConfigParser.NoOptionError: No option 'videoswitch' in section: 'Options'

**Comment by neerajrajpoot** [comment]
After adding the options in config.ini file issue got resolved. I didn't find the information regarding the configuration file anywhere. 
Options which i have added were : 

videoswitch = True
audioswitch = True
mosueswitch = True
followmouseswitch = True

**Comment by kode54** [comment]
It appears the configuration skeleton creates those options as:

```
videocheck = True
audiocheck = True
mousecheck = True
followmousecheck = False
```
