### ISSUE TITLE
Issues and workaround while trying to install/run on Pop!_OS 18.10 with Gnome 3.30 and Wayland

### ISSUE THREAD

**Issue by aral** [foss-project/green-recorder#114]
In case it helps, I did a write up of my experience:

https://ar.al/2019/01/01/getting-green-recorder-running-on-wayland-under-gnome-on-ubuntu-18.10-based-systems/

**Comment by mhsabbagh** [comment]
Thank you, I'll take a look on each of them (most are already reported on the issues page).
