### ISSUE TITLE
Version 3.2.1 no longer working on Ubuntu 18.04

### ISSUE THREAD

**Issue by dietmarw** [foss-project/green-recorder#123]
After the latest upgrade to 3.2.1 I noticed that:
 - mp4 is no longer provided as a recording format
 - recording does not work. No file is created.

Running green-recorder from the command line and doing a test recording the only error like message I could see are:

```
Traceback (most recent call last):
  File "/usr/bin/green-recorder", line 463, in recordclicked
    record()
  File "/usr/bin/green-recorder", line 319, in record
    RecordXorg()
  File "/usr/bin/green-recorder", line 175, in RecordXorg
    recorderindicator()
  File "/usr/bin/green-recorder", line 107, in recorderindicator
    indicator.set_secondary_activate_target(stoprecordingbutton)
NameError: global name 'stoprecordingbutton' is not defined
```
and
```
[x11grab @ 0x55de43befb60] Stream #0: not enough frames to estimate rate; consider increasing probesize
```

The previous version, 3.2.0, worked flawlessly. Is there any way to role back using the ppa?

**Comment by dietmarw** [comment]
Having played around with the source packages (without success), now suddenly the ppa version 3.2.1 is finally creating an output file.

Only thin that is still missing is the mp4 support.

**Comment by mhsabbagh** [comment]
Ehm, it seems mp4 format was removed by mistake since Mar, 2018: https://github.com/foss-project/green-recorder/commit/e080915ce0fc2061d94e433ca9d05155ca94140b#diff-4c90e27f97c90b40b30fc236fbcf2713

I will work on releasing 3.2.2 at the weekend.

**Comment by dietmarw** [comment]
Excellent!

**Comment by dietmarw** [comment]
It looks like the 3.2.2 release forgot to update the "About Green Recorder" Screen. That still says 3.2.1 when I definitely have 3.2.2 installed.

**Comment by mhsabbagh** [comment]
True, I'll make sure to avoid that in the future.
