### ISSUE TITLE
Archlinux renamed python2-pydbus to python2-dbus

### ISSUE THREAD

**Issue by pablodoramas** [foss-project/green-recorder#128]
In order to make it work, I had to change the following import sentence:
from:
    `22  from pydbus import SessionBus`
to:
    `22  from dbus import SessionBus`

**Comment by mhsabbagh** [comment]
@unixfox Is this the case? Should we change the dependencies on Arch package accordingly?

Later in the /usr/bin/green-recorder file I can create a try;except to handle this case.

**Comment by unixfox** [comment]
@pablodoramas I just published a new update to the AUR package please do let me know if that fixes the issue.
