### ISSUE TITLE
Link to website from About menu option is broken

### ISSUE THREAD

**Issue by gus-fabacus** [foss-project/green-recorder#132]
When following the link to the website https://foss-project.com), the certificate is invalid and if trying to access the URL http://foss-project.com/ the site doeen't seem to be valid.

**Comment by mhsabbagh** [comment]
FOSS Project is dead, and also its website. I also won't renew that domain name.

We just have to replace the URL in the about page to this GitHub page.

**Comment by gus-fabacus** [comment]
Hi, it makes sense. This could potentially be the diff with the update.
Thanks
```diff --git a/green-recorder b/green-recorder
index 68447b5..1ead60d 100755
--- a/green-recorder
+++ b/green-recorder
@@ -1,7 +1,7 @@
 #!/usr/bin/python
 # -*- coding: utf-8 -*-
 
-# FOSS Project <https://foss-project.com>, 2017, 2018.
+# FOSS Project <https://github.com/foss-project/green-recorder>, 2017, 2018.
 # Green Recorder is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
 # the Free Software Foundation, either version 3 of the License, or
@@ -399,7 +399,7 @@ aboutdialog.set_license("Green Recorder is free software: you can redistribute i
 aboutdialog.set_comments(_("A simple screen recorder for Linux desktop. Supports Wayland & Xorg."))
 aboutdialog.set_authors(['M.Hanny Sabbagh <mhsabbagh@outlook.com>','Alessandro Toia <gort818@gmail.com>','Patreon Supporters: Ahmad Gharib, Medium,\nWilliam Grunow, Alex Benishek.'])
 aboutdialog.set_artists(['Mustapha Assabar'])
-aboutdialog.set_website("https://foss-project.com")
+aboutdialog.set_website("https://github.com/foss-project/green-recorder")
 aboutdialog.set_logo_icon_name("green-recorder")
 windowgrabbutton.set_label(_("Select a Window"))
 areagrabbutton.set_label(_("Select an Area"))
```

**Comment by ei8fdb** [comment]
@mhsabbagh Hi there, does that mean the blogposts there will also be lost? Or will they be available on a new domain?

**Comment by Jpfonseca** [comment]
@ei8fdb  seems the blogposts are available [here](https://fosspost.org/)

**Comment by mhsabbagh** [comment]
@ei8fdb What blog posts are you talking about? The ones in FOSS Post? FOSS Post is still operating and will continue to do so.

**Comment by ei8fdb** [comment]
> What blog posts are you talking about? The ones in FOSS Post? 

No, I was talking about the ones on FOSS-Project, which I now know are also posted to FOSSPost.

> FOSS Post is still operating and will continue to do so.
👍 thanks.
