### ISSUE TITLE
Option to change default location from Videos to Desktop?

### ISSUE THREAD

**Issue by orschiro** [foss-project/green-recorder#29]
Dear all, 

I might just have overlooked it. 

Ist it possible?

**Comment by julianrichen** [comment]
[The default video path is set to the XDG VIDEOS directory](https://github.com/green-project/green-recorder/blob/e4fe16c8d27493fb2cc2a3dc7d14fc76da0bf47d/green-recorder#L32):
```python
# Get the current name of the Videos folder
VideosFolder = GLib.get_user_special_dir(GLib.USER_DIRECTORY_VIDEOS) 
```

Doesn't seem like it's changeable. Would either require setting-up [gsetting/gschema](https://developer.gnome.org/gio/stable/GSettings.html) (preferred, [tutorial](https://developer.gnome.org/GSettings/)) or using [GKeyFile](https://developer.gnome.org/glib/stable/glib-Key-value-file-parser.html) with settings.

**Comment by orschiro** [comment]
Maybe a user config file to set the default directory as well as other useful settings such as "disable microphone" by default, for example?

**Comment by mhsabbagh** [comment]
Currently not available. We'll need to create a small config file under /home/user/.config/green-recorder/green-recorder.ini which would contain the current defaults. Later from the program side an option to modify it could be added. But you know, it takes some time :)

**Comment by orschiro** [comment]
> Currently not available. We'll need to create a small config file under /home/user/.config/green-recorder/green-recorder.ini which would contain the current defaults

This would be already fantastic! I don't think it is too much expected from the user to edit this file by hand. :-)

**Comment by mhsabbagh** [comment]
Sure, if it was created, a "preferences" window would be created as well to enable the user to adjust the defaults beside some other stuff. :)

**Comment by mhsabbagh** [comment]
Done in 3.0
