### ISSUE TITLE
GIF as an output format

### ISSUE THREAD

**Issue by PieterO** [foss-project/green-recorder#38]
This is a very nice piece of software, thanks for writing it.

Is there any way of adding to the dropdown a .gif option? Would make it easier as I currently convert from .mkv to separate .jpeg's (at a lower framerate), then convert to a .gif using imagemagick.

If there is an easier way of doing this or a button I am missing I apologise.

**Comment by julianrichen** [comment]
`peek` would probably fit your needs better if you need a GIF recorder:
https://github.com/phw/peek

It's also a GTK3 application.

**Comment by mhsabbagh** [comment]
Adding GIF is actually possible. It's supported by ffmpeg. However, the resulting GIF size is so massive; tens of megabytes for just a 10-20 seconds GIF. I was planning into looking into the matter and maybe using some extra compression and other libraries or different color palette to reduce that size.

**Comment by orschiro** [comment]
Good point regarding the mentioning of Peek. 

It does the GIF part very well. Maybe we can learn something from them in that regard?

**Comment by mhsabbagh** [comment]
Yep. I am gonna check it in a while.

**Comment by PieterO** [comment]
@julianrichen Thanks for helping me fix my problem, made my day better :+1: . Great tool if people haven't tried it out.

**Comment by mhsabbagh** [comment]
GIF support is now available in 3.0
