### ISSUE TITLE
The "Select Area" Feature Is Extremely Hard To Work With Under Ubuntu 17.04

### ISSUE THREAD

**Issue by kenshiwara** [foss-project/green-recorder#40]
![screenshot](https://user-images.githubusercontent.com/12446892/27673498-9c2c6c5c-5cd3-11e7-8ba4-852eabb595dd.png)
Hello!

Please check the report below:

**Description:** It is extremely hard to specify the recording area under Kubuntu 17.04. The gray box is very hard to scale and its alpha is 100% - completely opaque. That means I can't see through it. On top of that, The title of that gray box prevents me from determining the top boundary of the selection properly. It is taking me too long to select an area for every video I have. Improving this feature will greatly elevate the power of this amazing tool.

**Possible Suggestions:**

1. Make the selection area transparent (Alpha: 0%) in order to see clearly what we are selecting.
2. Remove the title bar from the gray box selection area in order to see the upper bound of the selection area clearly.
3. The selection area must be scaled easily from any side without struggling to hit the mouse from its corners. A perfect example of such a feature can be found in the free and open source "Shutter" screenshot program. The selection box is clear and can be easily adjusted from any side or position.

**Note:** The reason why I am reporting those suggestions in the bugs section is because I suspect there is some kind of bug that is rendering it like that on my system.

**System Details:**
- **OS:** Ubuntu 17.04 zesty
- **Kernel:** x86_64 Linux 4.10.0-24-generic
- **Resolution:** 3840x2160
- **DE:** KDE5
- **WM:** KWin
- **CPU:** Intel Core i5-6500 CPU @ 3.6GHz
- **GPU:** GeForce GTX 1050 Ti
- **RAM:** 5606MiB / 15979MiB

Thanks in advance for reading my notes and suggestions.

**Comment by mhsabbagh** [comment]
Hello and thank you for taking time to report about this.

The window is transparent. I am not sure why it's not like that on KDE. On all the other interfaces, you can see through the area chooser window.

However I am with you about the window title bar, it's blocking selecting upper parts of the screen. I will try to work on a fix.

**Comment by raphaelh** [comment]
I've got the same issue under Ubuntu 19.04 Xfce, the window is grey
