### ISSUE TITLE
Update AUR package

### ISSUE THREAD

**Issue by mhsabbagh** [foss-project/green-recorder#45]
@unixfox Can you please update the AUR package with the new version dependencies?

**Comment by unixfox** [comment]
Done: https://aur.archlinux.org/cgit/aur.git/commit/?h=green-recorder-git&id=17e1b95cae2ec502447aaee70cdd2233c4ce0f7a
You don't need to create an issue on your repo, you just have to [submit a comment on the page of my package]((https://aur.archlinux.org/packages/green-recorder-git#news)) and I'll receive a notification on my email address.

**Comment by mhsabbagh** [comment]
Thanks! :-)
