### ISSUE TITLE
When installing the new green-recorder (-.-) version 3

### ISSUE THREAD

**Issue by jairusan** [foss-project/green-recorder#46]
When installing the new version from the FOSS PPA, I get the error when starting green-recorder:

**$ green-recorder 
Traceback (most recent call last):
  File "/usr/bin/green-recorder", line 66, in <module>
    DisplayServer = os.environ["XDG_SESSION_TYPE"]
  File "/usr/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'XDG_SESSION_TYPE'**

Version 2 works fine, look forward to testing this version 3.x.x once the issue is resolved.

Sincerely,

**Comment by mhsabbagh** [comment]
What distribution do you use and on what interface?

**Comment by jairusan** [comment]
Hello there mhsabbagh,

I use Linux Mint18 64bit in cinnamon desktop.

Hope that help, let me know if you need any additional information, happy to help.

Sincerely,

**Comment by jairusan** [comment]
To answer your question about systemd, I believe I do.

![system-linux-mint18](https://user-images.githubusercontent.com/5609312/29006098-227deb6e-7b24-11e7-8da8-c80dcec5c09b.png)

Sincerely,

**Comment by jairusan** [comment]
Here is some additional info:

_sudo stat /proc/1/exe
  File: '/proc/1/exe' -> '/lib/systemd/systemd'
  Size: 0         	Blocks: 0          IO Block: 1024   symbolic link
Device: 4h/4d	Inode: 8728922     Links: 1
Access: (0777/lrwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2017-08-06 14:28:48.635969495 +0900
Modify: 2017-08-06 13:58:48.558598581 +0900
Change: 2017-08-06 13:58:48.558598581 +0900
 Birth: -_

Sincerely,

**Comment by mhsabbagh** [comment]
The problem is that your system didn't set the $XDG_SESSION_TYPE variable. Which we use to detect if you are running Wayland or Xorg: https://www.freedesktop.org/software/systemd/man/pam_systemd.html

This is not the case here on Fedora 26, Ubuntu 17.04 and openSUSE Tumbleweed.

Can you try to run the service manually?

    sudo service systemd-logind start

**Comment by jairusan** [comment]
After running the command above, it still error out:

_jair@x1 ~ $ sudo service systemd-logind start
jair@x1 ~ $ green-recorder 
Traceback (most recent call last):
  File "/usr/bin/green-recorder", line 66, in <module>
    DisplayServer = os.environ["XDG_SESSION_TYPE"]
  File "/usr/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'XDG_SESSION_TYPE'_

Sincerely,

**Comment by jairusan** [comment]
I am based in Tokyo, Japan I need to go to bed.  I will check for your suggestions, otherwise, will continue testing version 2.x.x

Thanks for the assistance,

**Comment by mhsabbagh** [comment]
I have pushed an update for it. Please check it and tell me later.

**Comment by jairusan** [comment]
Hello there,

_jair@x1 ~ $ sudo apt-cache policy green-recorder
green-recorder:
  Installed: (none)
  Candidate: 3.0.1.2
  Version table:
     3.0.1.2 500
        500 http://ppa.launchpad.net/fossproject/ppa/ubuntu xenial/main amd64 Packages
        500 http://ppa.launchpad.net/fossproject/ppa/ubuntu xenial/main i386 Packages
jair@x1 ~ $ sudo apt install green-recorder
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  python-pydbus
The following NEW packages will be installed:
  green-recorder python-pydbus
0 upgraded, 2 newly installed, 0 to remove and 37 not upgraded.
Need to get 31.9 kB of archives.
After this operation, 170 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 http://ppa.launchpad.net/fossproject/ppa/ubuntu xenial/main amd64 python-pydbus all 0.6.0.1 [12.1 kB]
Get:2 http://ppa.launchpad.net/fossproject/ppa/ubuntu xenial/main amd64 green-recorder all 3.0.1.2 [19.8 kB]
Fetched 31.9 kB in 1s (25.9 kB/s)         
Selecting previously unselected package python-pydbus.
(Reading database ... 883385 files and directories currently installed.)
Preparing to unpack .../python-pydbus_0.6.0.1_all.deb ...
Unpacking python-pydbus (0.6.0.1) ...
Selecting previously unselected package green-recorder.
Preparing to unpack .../green-recorder_3.0.1.2_all.deb ...
Unpacking green-recorder (3.0.1.2) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu5.1) ...
Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Setting up python-pydbus (0.6.0.1) ...
Setting up green-recorder (3.0.1.2) ...
jair@x1 ~ $ green-recorder 
Traceback (most recent call last):
  File "/usr/bin/green-recorder", line 66, in <module>
    DisplayServer = os.environ["XDG_SESSION_TYPE"]
  File "/usr/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'XDG_SESSION_TYPE'_

Same problem...

Sincerely,

Good night,

**Comment by mhsabbagh** [comment]
You didn't get the update yet. Launchpad servers take time to publish the new update. Try in 15 minutes (or whenever later you want).

**Comment by jairusan** [comment]
Hello mhsabbagh,

The 3.0.2 update you told me about, fixed the issue.  See the screenshot attached.

Thank you very much!
![green-recorder-2](https://user-images.githubusercontent.com/5609312/29014352-952814a0-7b83-11e7-89ac-494ba7e52457.png)

![green-recorder-1](https://user-images.githubusercontent.com/5609312/29014357-9bb6c820-7b83-11e7-9ca6-070497c9e2e4.png)

**Comment by jairusan** [comment]
Hello there,

Looks like you pushed another update >> 3.0.3

I just wanted to confirm that it also works.  Thank you for your hard work!

Sincerely,

**Comment by mhsabbagh** [comment]
You are welcome :)
