### ISSUE TITLE
Blank settings window

### ISSUE THREAD

**Issue by ettavolt** [foss-project/green-recorder#54]
... if settings window is closed via window control, not 'close' button at the bottom. 3.0.1.2.r2.ge7f877d

**Comment by ettavolt** [comment]
... if settings window is closed via window control, not 'close' button at the bottom. 3.0.1.2.r2.ge7f877d

**Comment by mhsabbagh** [comment]
Which is why we included a close button. This is a weird bug in GTK. Not sure about a fix for it.

**Comment by ettavolt** [comment]
What about catching [delete-event](https://developer.gnome.org/gtk3/stable/GtkWidget.html#GtkWidget-delete-event)? There is even a [premade handler](https://developer.gnome.org/gtk3/stable/GtkWidget.html#gtk-widget-hide-on-delete).

**Comment by mhsabbagh** [comment]
For some reason they don't seem to work with me. Catching `delete-even` changed nothing and `preferenceswindow.hide_on_delete()` didn't add anything. Not sure if I am doing it wrong or.

**Comment by ettavolt** [comment]
Turns out [it's not that simple under python](https://stackoverflow.com/a/21688771). This way it seem to work:
```python
def hide_on_delete(widget, event):
    widget.hide()
    return True

preferenceswindow.connect("delete-event", hide_on_delete)
```
