### ISSUE TITLE
GPU acceleration

### ISSUE THREAD

**Issue by realh** [foss-project/green-recorder#57]
Does GNOME Screencast use GPU acceleration where possible? I see that in Wayland green-recorder overrides the gstreamer pipeline to use VP8. It should be quite easy to make it use VA-API if gst doesn't automatically try to do that itself. I gather VA-API encoding might be a bit dodgy on non-Intel GPUs, but it could be quite useful if you do have the right hardware.

**Comment by mhsabbagh** [comment]
I am not sure if I understand what you are talking about. More explanation would be helpful

**Comment by realh** [comment]
As far as I know green-recorder and GNOME Screencast both only support software encoding, which is why you've found the CPU usage too high with VP9 (on my Core i7-6500u GNOME Screencast uses about 250%-300% to encode its native resolution of 2560x1440).

Modern GPUs (including APUs such as Intel's Core i series) support more efficient "hardware accelerated" decoding and encoding, so it would be handy if green-recorder could support that - this is a feature request rather than a bug report.

Encoding support in the Linux APIs does lag behind decoding support, but I think it should be reliable enough with VAAPI on an Intel, and it looks like it's supported in gstreamer-vaapi:

    $ gst-inspect-1.0 vaapi
    Plugin Details:
      Name                     vaapi
      Description              VA-API based elements
      Filename                 /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstvaapi.so
      Version                  1.12.2
      License                  LGPL
      Source module            gstreamer-vaapi
      Source release date      2017-07-14
      Binary package           gstreamer-vaapi
      Origin URL               http://bugzilla.gnome.org/enter_bug.cgi?product=GStreamer

      vaapijpegdec: VA-API JPEG decoder
      vaapimpeg2dec: VA-API MPEG2 decoder
      vaapih264dec: VA-API H264 decoder
      vaapivc1dec: VA-API VC1 decoder
      vaapivp8dec: VA-API VP8 decoder
      vaapih265dec: VA-API H265 decoder
      vaapipostproc: VA-API video postprocessing
      vaapidecodebin: VA-API Decode Bin
      vaapisink: VA-API sink
      vaapimpeg2enc: VA-API MPEG-2 encoder
      vaapih265enc: VA-API H265 encoder
      vaapivp8enc: VA-API VP8 encoder
      vaapijpegenc: VA-API JPEG encoder
      vaapih264enc: VA-API H264 encoder

      14 features:
      +-- 14 elements

So it should only require a small change to the pipeline. But working out whether the codec you want is supported and/or falling back to an older one would be a bit more difficult. Also, it could be undesirable in some cases, if it ties up GPU resources that compromise its gaming performance.

**Comment by samdroid-apps** [comment]
Hey @realh  - I love the idea.  Do you know what changes to the pipeline are required to support VA-API?

We could also probably overhaul how the codecs work now; so there are more options I suppose.

**Comment by mhsabbagh** [comment]
I don't know for VAAPI. There are however other encoders which we can use and provide. For example we simple can use the current pipeline as it is but with changing vp8enc into vp9enc to support V9. There's also avimux (for AVI) and videoconvert (for MP4). We can support those on GNOME Wayland. But as for the defaults, we'd keep with supporting as much as user base as possible (the older hardware).

**Comment by realh** [comment]
I don't know exactly what would need to be changed in the pipeline, but I think it should be quite simple. I'll see if I can work it out, but I might not have much time this week. There is a problem with VAAPI on Wayland in that it seems to fail to initialise the driver if you open it the normal way, but there is a way around this, which is known to mpv at least (you have to use --vo=opengl --opengl-backend=wayland). gstreamer-vaapi may need patching to make the same thing possible with it.

@mhsabbagh I agree about not changing the defaults. Detecting what's available and actually working is a bit too difficult at the moment. I would propose providing an option "for advanced users" to set the pipeline, with examples shown in the documentation or wiki.

**Comment by realh** [comment]
I tried changing the pipeline to use vaapivp8enc and suffered a complete system freeze. gstreamer-vaapi decoders aren't working either for me in Wayland ATM (albeit with less drastic symptoms) so I've reported a [bug in Debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=873343). I don't know yet whether it's upstream.

**Comment by mhsabbagh** [comment]
I believe then it's too early for such a change (or an option). Will check it in the future.
