### ISSUE TITLE
Some troubleshooting article would be very helpful

### ISSUE THREAD

**Issue by adeptg** [foss-project/green-recorder#58]
Hello
First of all: thanks for your work!
I've tried to use green recorder to capture my screen and sound from my headphones (not a mic, just what I hear). And I was unable to do it - video is just silent.
So any small article how to troubleshoot would be very helpful. Thanks

**Comment by mhsabbagh** [comment]
Please run "green-recorder" from the command line and see if you get any errors. You should choose the right input device from the sound menu according to your pulseaudio installation. If you chose to record only what you "hear", then the video will be silent until you trigger something from the system's output device (for example try to watch a Youtube video).
