### ISSUE TITLE
app doesn't run on fedora 26

### ISSUE THREAD

**Issue by christianbueno1** [foss-project/green-recorder#59]
hello 
<pre><code>
 tony  ~  green-recorder 
/bin/sh: xdpyinfo: command not found
You are recording on: wayland
/bin/sh: pacmd: command not found
Traceback (most recent call last):
  File "/usr/bin/green-recorder", line 428, in <module>
    audiosourcesnames = audiosourcesnames.split("\n")[:-1]
NameError: name 'audiosourcesnames' is not defined
</pre></code>

**Comment by mhsabbagh** [comment]
Did you install it from the repository? You are missing some dependencies: xdpyinfo (from xorg-utils) and pacmd (from pulseaudio-utils).
