### ISSUE TITLE
Audio out of sync

### ISSUE THREAD

**Issue by lozobo** [foss-project/green-recorder#60]
Hi

I'm on Fedora 26 with Wayland, building the rpm from source and my audio goes out of sync.

I've traced the problem on this two ffmpeg flags "-strict -2", which i'm not sure what they should do (I haven't found nor in the man or in the documentation).
The commit which added the bug was this [https://github.com/foss-project/green-recorder/commit/1a5c8472a2611b0858b44eab7aac75a2d4ea6ff0](url).

I've tested the same version without those flag and the audio it's ok. I can reproduce it every time.

**Comment by mhsabbagh** [comment]
-strict -2 is used for Ubuntu based distributions. Their ffmpeg version doesn't support some codecs and suggests adding -strict -2 to allow experimental features. That's why it was enabled there. However, on Wayland and since we are recording only WebM. We don't need -strict -2. Fixed.
