### ISSUE TITLE
Recording at high fps, mouse movement still choppy

### ISSUE THREAD

**Issue by aditiapratama** [foss-project/green-recorder#62]
I tried to record screen on wayland at 60 fps, but it seems my mouse movement on video a little bit laggy, seems like it was using 15fps or something.

Is this known issue?

**Comment by mhsabbagh** [comment]
I didn't personally see this issue. I believe nobody else mentioned it here too. Remember that on Wayland (GNOME), Green Recorder uses the built-in screencasting tool in GNOME itself. Nothing from outside.

**Comment by fzwoch** [comment]
For the record: GNOME ScreenCast hard codes the cursor position interval to 100 ms.

`GNOME/gnome-shell/blob/master/src/shell-recorder.c`:
```
/* The time (in milliseconds) between querying the server for the cursor
 * position.
 */
#define UPDATE_POINTER_TIME 100
```

I don't see a way to change this. Maybe take this to the GNOME guys to update the cursor position for each frame.
