### ISSUE TITLE
`data_files` installed in the wrong path

### ISSUE THREAD

**Issue by eyalzek** [foss-project/green-recorder#63]
On ubuntu 16.10, using the latest `master` branch (https://github.com/green-project/green-recorder/archive/master.zip) and running `python setup.py install`, I saw the following error afterwards when trying to run `green-recorder`:

```
You are recording on: x11
Traceback (most recent call last):
  File "/usr/local/bin/green-recorder", line 300, in <module>
    builder.add_from_file("/usr/share/green-recorder/ui.glade")
GLib.Error: g-file-error-quark: Failed to open file '/usr/share/green-recorder/ui.glade': No such file or directory (4)
```

after a bit of debugging I noticed the the `data_files` were installed under `/usr/local/share/` instead of `/usr/share/`. After manually moving `ui.glade` and `green-recorder.png` to the correct folder, the program runs as expected.

This stackoverflow thread explains the problem:
https://stackoverflow.com/a/20370738

**Comment by gort818** [comment]
I just tested this, python script was installed in `/usr/bin` and data was installed in `/usr/share/`. I checked the setup.py file everything seems to be in order.

**Comment by mhsabbagh** [comment]
Same. It was installed under /usr/share.
