### ISSUE TITLE
Overwrite file notification requested

### ISSUE THREAD

**Issue by stevendholden** [foss-project/green-recorder#64]
I was doing some experimenting and I realized that if I didn't change the name of the file of a previous recording it would just get automatically re-written and I'd loose the previous recording.

If this happens to others (not an isolated problem on my system) then I'd recommend a notificiation to the user (are you sure you want to overwrite?  no = let's you change file, yes = overwrite).

Thanks!

**Comment by mhsabbagh** [comment]
You could leave it empty. In this way, the file name will be the current time and date.

But yea, it should ask a confirmation if a file exists with same name.

**Comment by gort818** [comment]
We could also just clear the entry box when a recording is stopped. 
Yeah confirmation would be nice, might work on this week if I have time :)

**Comment by gort818** [comment]
@stevendholden @mhsabbagh  I just created a pull request for this issue.
