### ISSUE TITLE
Issue with repo

### ISSUE THREAD

**Issue by jreiners** [foss-project/green-recorder#67]
Getting the following error, tried on both Fedora 25 and Fedora 26. Did the repo change?

✔ 09:51 justinpc ~ (master #%) 0.002s
$ sudo dnf config-manager --add-repo http://download.opensuse.org/repositories/home:mhsabbagh/Fedora_25/home:mhsabbagh.repo
[sudo] password for justin: 
Adding repo from: http://download.opensuse.org/repositories/home:mhsabbagh/Fedora_25/home:mhsabbagh.repo

✔ 09:51 justinpc ~ (master #%) 5.100s
$ sudo dnf install green-recorder
Failed to synchronize cache for repo 'home_mhsabbagh', disabling.     --:-- ETA
Last metadata expiration check: 1:15:40 ago on Wed Sep 13 08:35:56 2017.
No package green-recorder available.
Error: Unable to find a match.

**Comment by mhsabbagh** [comment]
I don't have this issue here on Fedora 26.
