### ISSUE TITLE
System Tray Icon Removal

### ISSUE THREAD

**Issue by mhsabbagh** [foss-project/green-recorder#68]
GNOME 3.26 removed system tray. It means that the recorder is no longer usable on GNOME 3.26, since it depends on the system tray icon in order to be able to stop recording.

I am thinking of removing the indicator from the program and depending only on a stop button in the main window itself. This is not nice however:

- Other interfaces will lose the feature although they support it.
- It's very much inconvenient to have to minimize the window manually after clicking the record button.
- If the window is closed by mistake, the recording will keep running in background, and there's no way to stop it.

Any other ideas are welcome.

**Comment by gort818** [comment]
Hmm I believe that the system tray is available as an extension , users would just have to install the extension before using green recorder.

**Comment by SafaAlfulaij** [comment]
> Other interfaces will lose the feature although they support it.

https://specifications.freedesktop.org/systemtray-spec/systemtray-spec-0.3.html
http://doc.qt.io/qt-5/qsystemtrayicon.html#isSystemTrayAvailable

> If the window is closed by mistake, the recording will keep running in background, and there's no way to stop it.

https://developer.gnome.org/hig/stable/dialogs.html.en

**Comment by mhsabbagh** [comment]
Removing the tray icon will also solve a lot of issues for us and will minimize the code.

There's an extension for GNOME Shell to get it back. But it's not there by default.

**Comment by thekyriarchy** [comment]
Wouldn't it be possible to have a tiny window that only contained a stop recording button? The window could be minimized like any other. Ideally it wouldn't be a normal window but a floating widget that could be hidden and restored similar to a window.

**Comment by mindaslab** [comment]
Yup i faced this problem in Ubuntu 17.10. I started to record and green recorder disappeared, I couldn't stop recording. I switched to Unity desktop and am using Kazam instead.

**Comment by bungabunga** [comment]
@mhsabbagh where can i find this extension? i looked around but i couldn't find it...

**Comment by mhsabbagh** [comment]
@bungabunga Here: https://extensions.gnome.org/extension/1031/topicons/
