### ISSUE TITLE
can't stop recording when choosing custom recording area

### ISSUE THREAD

**Issue by ITwrx** [foss-project/green-recorder#70]
i have dual monitors and if i leave the recording area settings as default, the green-recorder icon is in gnome system tray so i can open green recorder gui back up to stop recording. unfortunately, if i choose my own record area, the system tray icon is not present even though green-recorder is still recording, as indicated by the red record icon in gnome volume control area(top right).
thanks

**Comment by pluma** [comment]
I have the same problem. The system tray icon doesn't show up if I set a recording area and when starting to record the app vanishes. Had to manually kill the process and delete the temporary file.
