### ISSUE TITLE
Green Recorder doesen't launch on Ubuntu 17.10

### ISSUE THREAD

**Issue by bungabunga** [foss-project/green-recorder#73]
> Traceback (most recent call last):
  File "/usr/bin/green-recorder", line 40, in <module>
    config.set('Options', 'folder', "file://" + GLib.get_user_special_dir(GLib.USER_DIRECTORY_VIDEOS))
TypeError: cannot concatenate 'str' and 'NoneType' objects

**Comment by gort818** [comment]
@bungabunga I will test this later on and get a fix for you.

**Comment by mhsabbagh** [comment]
This is probably because you have a missing XDG_VIDEOS_DIR variable in your /home/user/.config/user-dirs.dirs

Can you please give me the output of the following command:

cat /home/$USER/.config/user-dirs.dirs

**Comment by bungabunga** [comment]
XDG_DESKTOP_DIR="$HOME/Desktop"
XDG_DOWNLOAD_DIR="$HOME/Downloads"

No, I don't have most of the default folders, as many others I find them limiting my workflow/freedom. Please don't make having Videos folder mandatory for using this great software.

**Comment by gort818** [comment]
Ok so if a user does not have XDG_VIDEOS_DIR , we can set the default dir to be the home dir.

**Comment by bungabunga** [comment]
That would be great!

**Comment by gort818** [comment]
@bungabunga @mhsabbagh  fixed here #74 :)

**Comment by gort818** [comment]
Also remove this file in your home dir before launching green-recorder .config/green-recorder/config.ini

**Comment by mhsabbagh** [comment]
Unfortunately this does fix it, but will break stuff for all the other users because you are modifying the config.ini file structure which they don't have. 

A better solution would be simply if GLib.USER_DIRECTORY_VIDEOS is None, then set it to " ".
