### ISSUE TITLE
Ubuntu 17.10 Recorder Freezes at Start

### ISSUE THREAD

**Issue by s3w47m88** [foss-project/green-recorder#75]
I'm using Green Recorder for the first time on a Razer Blade 14" running Ubuntu 17.10. When I click the record button the entire computer freezes indefinitely. Any support would be appreciated, thank you!

**Comment by PanadeEdu** [comment]
I have the exact same behaviour. 
Another thing I noticed: when I tried using xorg instead of wayland, it froze after login in the same manner. 

I asume at this point it is a problem with wayland. But maybe someone with more knowledge can shine light on that.

**Comment by mhsabbagh** [comment]
Green Recorder uses the built-in screencasting tool in GNOME itself. There's a known issue with some graphics cards that causes the system to freeze directly when trying to record. It has been there for a while. Please search for it on GNOME Bugzilla.

Thus, this is about the upstream GNOME code, not Green Recorder.

**Comment by pfctdayelise** [comment]
I couldn't find any relevant issues in Bugzilla, so I filed a new issue. https://bugzilla.gnome.org/show_bug.cgi?id=790008

**Comment by iambumblehead** [comment]
Yikes every screen recording software I've tried installing on an xps13 causes the computer to freeze

**Comment by phw** [comment]
@iambumblehead Use X11 isntead of Wayland as a workaround
