### ISSUE TITLE
Recording running status icon in Budgie-DE malforming the budgie-panel

### ISSUE THREAD

**Issue by ayanb1991** [foss-project/green-recorder#77]
I am using Ubuntu-Budgie 17.10 and whenever I am starting the recording the recording status indicator icon appearing in the budgie-panel and malforming the budgie-panel. Working nice on XFCE and Cinnamon. May be a issue of budgie DE but still please have a look. 
![budgie_issue](https://user-images.githubusercontent.com/14938120/31984797-646d2130-b980-11e7-8042-5df45012b374.png)

**Comment by fossfreedom** [comment]
The issue here is that the icon is too large - the appindicator spec mandates that the icon-size for app indicators should be 22x22

We (Ubuntu Budgie) can overcome the sizing issues if the icon was a .svg - but cannot automatically resize with png images.

**Comment by ayanb1991** [comment]
Thanks for replying, I got what you are saying. But this thing works well on XFCE and Cinnamon environments. I have tested it. May be XFCE and Cinnamon is presenting the appindicator in a different way. right? So what can be the solution to it?

**Comment by fossfreedom** [comment]
Software here needs to fix it. Suggestions are in my reply above
