### ISSUE TITLE
Green-recorder-download-and-install-failed

### ISSUE THREAD

**Issue by jamesray1** [foss-project/green-recorder#78]
See what I've copied and pasted from the terminal (on Artful): https://gist.github.com/jamesray1/ef06da0bd58c88959f8136a47ad0f61b#file-gistfile1-txt.

**Comment by jamesray1** [comment]
OK, that's pretty vague and thus not very helpful for me. I don't really want to spend a lot of time looking into this. Any way, there is a bug with GNOME that needs to be fixed before I can use any screen recording function.

**Comment by andrewhowdencom** [comment]
I also had this from copy pasta'ing it. I'm on Debian 9, though -- for some reason, the PGP key didn't import. Had to do it manually from Ubuntu keyservers.

**Comment by neerajrajpoot** [comment]
I also faced some issues while installation, At last i installed the greenrecorder with help of setup.py

Err:3 http://ppa.launchpad.net/fossproject/ppa/ubuntu disco Release                                                                                  
  404  Not Found

**Comment by jamesray1** [comment]
Unsubscribing, using Manjaro now, haven't needed a screen recorder.
