### ISSUE TITLE
[Fedora] Copr repo?

### ISSUE THREAD

**Issue by DarthWound** [foss-project/green-recorder#79]
Hello, thank you for this recorder, useful for game recording under Wayland.

However it seems that a Copr exists [here](https://copr.fedorainfracloud.org/coprs/mhsabbagh/greenproject/), but no builds inside. I know that there is an OBS repo but no builds for F27 and using Copr would be better anyway.

Thank you :)

**Comment by mhsabbagh** [comment]
We already had a Copr repo, but Fedora removed it, and all the packages, and the whole project.

They didn't even bother to send an email btw, just removal directly. Later I learned from some people that the reason may be ffmpeg (patents stuff related to legal issues). After that, we switched to OBS.

**Comment by DarthWound** [comment]
Oh :disappointed: I understand perfectly, thank you for clarification.
I'll wait for F27 builds from OBS so.
