### ISSUE TITLE
fedora 27 package

### ISSUE THREAD

**Issue by AmarOk1412** [foss-project/green-recorder#84]
Hi!

I see in the README that green-recorder got a Fedora 224/25/26 package, and now Fedora got a 27 version.

The package will be available? Or do you want to migrate to snap (where the package already exists)?

Have a nice day,

**Comment by mhsabbagh** [comment]
Should be coming soon (This weekend, hopefully).

**Comment by mhsabbagh** [comment]
The package is now available for Fedora 27. Sorry for taking this so much time, life is indeed hard!

**Comment by AmarOk1412** [comment]
aha np. thx!
