### ISSUE TITLE
clicking on Record (b)locks my computer. Hard reboot needed

### ISSUE THREAD

**Issue by sanderjo** [foss-project/green-recorder#85]
On my Ubuntu 17.10 (fully updated), clicking on Reboot locks my computer. Mouse does not move anymore, CTRL-C does not work. Only a power-reboot works.

green-recorder version 3.1 from the PPA.

Tips how to solve this?

EDIT: When I select X at startup, no problems. So Wayland is a / the cause?

![green-recorder lock](https://user-images.githubusercontent.com/1273502/35487022-22606df0-0477-11e8-9740-19c987262c87.png)

**Comment by mhsabbagh** [comment]
This is similar to many other reported problems regarding recording on GNOME; It is a bug in GNOME itself, not from Green Recorder. It was also reported multiple times on GNOME bugzilla. You can search for it there. (On some specific hardware, the recording takes all resources and freezes the system).

**Comment by GCorbel** [comment]
Here is the link for the bug in GNOME bugzilla : https://bugzilla.gnome.org/show_bug.cgi?id=790008
