### ISSUE TITLE
Application inaccessible after hitting Record in LXDE

### ISSUE THREAD

**Issue by meowsus** [foss-project/green-recorder#86]
When recording with Green Recorder, the application helpfully hides itself, as not to sully the pixels of the produced screencast with its presence. 

Unfortunately, in LXDE, it hides itself in a completely inaccessible place. This means that ffmpeg is now just recording indefinitely until its process is killed.

Possible solutions might be:
- I completely missed something
- Send Green Recorder to the background, rather than to a Gnome/Unity exclusive indicator zone
- Add a "Minimize to tray" option

**Comment by meowsus** [comment]
Great work, by the way. This is one of the best screen capture applications I've ever used.

**Comment by mhsabbagh** [comment]
You got to be using an old version of Green Recorder because in the newer version, the system tray icon was removed completely. Thus, you can stop the recording using the "Stop" button from the program's window.

**Comment by meowsus** [comment]
@mhsabbagh I grabbed it off of your PPA: https://launchpad.net/~mhsabbagh/+archive/ubuntu/greenproject

I just got it off the foss-project PPA and everything seems fine. Strange.

Thanks!
