### ISSUE TITLE
App unable to locate ALSA driver when started from command line

### ISSUE THREAD

**Issue by Shappiro** [foss-project/green-recorder#88]
`green-recorder`

`/bin/sh: 1: aserver: not found`
`('No alsa found', 127)`
`E: [pulseaudio] pid.c: Daemon already running.`
`E: [pulseaudio] main.c: pa_pid_file_create() failed.`

Even if `alsa-utils` is installed.

That's under Ubuntu 16.04

App works perfectly fine (sometimes feels too good to be true) when loaded from GUI.

**Comment by mhsabbagh** [comment]
You are using an extremly old version of Green Recorder. The current version only supports and uses PulseAudio.
