### ISSUE TITLE
area-selected recording fails to write to file

### ISSUE THREAD

**Issue by hdbhdb** [foss-project/green-recorder#98]
I'm having issues with the area select feature in the latest ppa package (3.1) on ubuntu 17.10 with wayland. After I select an area and press record, the taskbar icon appears, but no video is actually written to file. After stopping the recording, the icon disappears from the taskbar as expected, but pressing play does nothing as there is no file. This issue only occurs when area select is used--recording the entire screen works fine.

**Comment by hdbhdb** [comment]
after some more experimenting, it seems that the issue only happens when the area select box is drawn so that it is touching the side of the screen--I'm assuming this is the same problem as #87 and the ppa hasn't been updated since then

**Comment by jwich71** [comment]
The issue still exists in F29 Wayland with the F28 green-recorder package. Please fix.
